abstract type OrdinaryDiffEqCache <: SciMLBase.DECache end
abstract type OrdinaryDiffEqConstantCache <: OrdinaryDiffEqCache end
abstract type OrdinaryDiffEqMutableCache <: OrdinaryDiffEqCache end
struct ODEEmptyCache <: OrdinaryDiffEqConstantCache end
struct ODEChunkCache{CS} <: OrdinaryDiffEqConstantCache end

ismutablecache(cache::OrdinaryDiffEqMutableCache) = true
ismutablecache(cache::OrdinaryDiffEqConstantCache) = false

# Unified scratch buffers held by every `OrdinaryDiffEqMutableCache`.
#
# Parameterized on the three buffer-array types every cache already
# carries — `uType`, `rateType`, `uNoUnitsType` — so a cache that declares
# `tmp_cache::TmpCache{uType, rateType, uNoUnitsType}` doesn't need to
# introduce a new type parameter.
#
# Fields are concrete (no `Union{T, Nothing}`) — every TmpCache slot is
# always preallocated. Non-adaptive caches that don't carry a unit-less
# scratch parameterize as `TmpCache{uType, rateType, Nothing}`, which
# makes the `atmp` field type `Nothing` (a singleton); the only valid
# value at that slot is `nothing`, and no array is allocated.
struct TmpCache{uType, rateType, uNoUnitsType}
    tmp       ::uType         # primary state scratch
    tmp2      ::uType         # secondary state scratch (was `utilde`)
    atmp      ::uNoUnitsType  # unit-less state scratch (error norms); `Nothing`
                              # for non-adaptive caches that don't need it
    rate_tmp  ::rateType      # primary rate scratch (was `linsolve_tmp`)
    rate_tmp2 ::rateType      # secondary rate scratch
end

"""
    build_tmp_cache(u, rate_prototype, uEltypeNoUnits; kwargs...)

Construct a `TmpCache`. Every slot is preallocated. Pass `Nothing` for
`uEltypeNoUnits` when the cache parameterizes its `tmp_cache` field as
`TmpCache{uType, rateType, Nothing}` — the atmp slot is then forced to
the singleton `nothing` and no array is allocated.

The `need_*` and `preallocate_init_dt_extras` kwargs are accepted but
ignored; they remain in the signature for source-level compatibility
with call sites generated by the migration script. They may be removed
in a follow-up.
"""
@inline function build_tmp_cache(u, rate_prototype,
        ::Type{uEltypeNoUnits};
        need_tmp::Bool = false,
        need_tmp2::Bool = false,
        need_atmp::Bool = false,
        need_rate_tmp::Bool = false,
        need_rate_tmp2::Bool = false,
        preallocate_init_dt_extras::Bool = true) where {uEltypeNoUnits}
    tmp = zero(u)
    tmp2 = zero(u)
    rate_tmp = zero(rate_prototype)
    rate_tmp2 = zero(rate_prototype)
    uT = typeof(u)
    rT = typeof(rate_prototype)
    if uEltypeNoUnits === Nothing
        return TmpCache{uT, rT, Nothing}(tmp, tmp2, nothing, rate_tmp, rate_tmp2)
    else
        atmp = similar(u, uEltypeNoUnits)
        recursivefill!(atmp, false)
        return TmpCache{uT, rT, typeof(atmp)}(tmp, tmp2, atmp, rate_tmp, rate_tmp2)
    end
end

# Don't worry about the potential alloc on a constant cache
get_fsalfirstlast(cache::OrdinaryDiffEqConstantCache, u) = (zero(u), zero(u))

mutable struct CompositeCache{T, F} <: OrdinaryDiffEqCache
    caches::T
    choice_function::F
    current::Int
end

function ismutablecache(cache::CompositeCache{T, F}) where {T, F}
    return eltype(T) <: OrdinaryDiffEqMutableCache
end

function get_fsalfirstlast(cache::CompositeCache, u)
    _x = get_fsalfirstlast(cache.caches[1], u)
    if first(_x) !== nothing
        return _x
    else
        return get_fsalfirstlast(cache.caches[2], u)
    end
end

mutable struct DefaultCache{T1, T2, T3, T4, T5, T6, A, F, uType} <: OrdinaryDiffEqCache
    args::A
    choice_function::F
    current::Int
    u::uType
    cache1::T1
    cache2::T2
    cache3::T3
    cache4::T4
    cache5::T5
    cache6::T6
    function DefaultCache{T1, T2, T3, T4, T5, T6, F, uType}(
            args, choice_function, current, u
        ) where {T1, T2, T3, T4, T5, T6, F, uType}
        return new{T1, T2, T3, T4, T5, T6, typeof(args), F, uType}(
            args, choice_function, current, u
        )
    end
end

function get_fsalfirstlast(cache::DefaultCache, u)
    return (cache.u, cache.u) # will be overwritten by the cache choice
end

function ismutablecache(
        cache::DefaultCache{
            T1, T2, T3, T4, T5, T6, A, F, uType,
        }
    ) where {T1, T2, T3, T4, T5, T6, A, F, uType}
    return T1 <: OrdinaryDiffEqMutableCache
end

function alg_cache(
        alg::CompositeAlgorithm, u, rate_prototype, ::Type{uEltypeNoUnits},
        ::Type{uBottomEltypeNoUnits}, ::Type{tTypeNoUnits}, uprev, uprev2, f, t,
        dt, reltol, p, calck,
        ::Val{V}, verbose
    ) where {V, uEltypeNoUnits, uBottomEltypeNoUnits, tTypeNoUnits}
    caches = __alg_cache(
        alg.algs, u, rate_prototype, uEltypeNoUnits, uBottomEltypeNoUnits,
        tTypeNoUnits, uprev, uprev2, f, t, dt, reltol, p, calck, Val(V), verbose
    )
    return CompositeCache(caches, alg.choice_function, 1)
end

function alg_cache(
        alg::CompositeAlgorithm{CS, Tuple{A1, A2, A3, A4, A5, A6}}, u,
        rate_prototype, ::Type{uEltypeNoUnits}, ::Type{uBottomEltypeNoUnits}, ::Type{tTypeNoUnits},
        uprev, uprev2, f, t, dt, reltol, p, calck,
        ::Val{V}, verbose
    ) where {
        CS, V, uEltypeNoUnits, uBottomEltypeNoUnits, tTypeNoUnits, A1, A2, A3, A4, A5, A6,
    }
    args = (
        u, rate_prototype, uEltypeNoUnits,
        uBottomEltypeNoUnits, tTypeNoUnits, uprev, uprev2, f, t, dt,
        reltol, p, calck, Val(V), verbose,
    )
    # Core.Typeof to turn uEltypeNoUnits into Type{uEltypeNoUnits} rather than DataType
    argT = map(Core.Typeof, args)
    T1 = Base.promote_op(alg_cache, A1, argT...)
    T2 = Base.promote_op(alg_cache, A2, argT...)
    T3 = Base.promote_op(alg_cache, A3, argT...)
    T4 = Base.promote_op(alg_cache, A4, argT...)
    T5 = Base.promote_op(alg_cache, A5, argT...)
    T6 = Base.promote_op(alg_cache, A6, argT...)
    cache = DefaultCache{T1, T2, T3, T4, T5, T6, typeof(alg.choice_function), typeof(u)}(
        args, alg.choice_function, 1, u
    )
    algs = alg.algs
    # If the type is a bitstype we need to initialize it correctly here since isdefined will always return true.
    if isbitstype(T1)
        cache.cache1 = alg_cache(algs[1], args...)
    end
    if isbitstype(T2)
        cache.cache2 = alg_cache(algs[2], args...)
    end
    if isbitstype(T3)
        cache.cache3 = alg_cache(algs[3], args...)
    end
    if isbitstype(T4)
        cache.cache4 = alg_cache(algs[4], args...)
    end
    if isbitstype(T5)
        cache.cache5 = alg_cache(algs[5], args...)
    end
    if isbitstype(T6)
        cache.cache6 = alg_cache(algs[6], args...)
    end
    return cache
end

# map + closure approach doesn't infer
@generated function __alg_cache(
        algs::T, u, rate_prototype, ::Type{uEltypeNoUnits},
        ::Type{uBottomEltypeNoUnits}, ::Type{tTypeNoUnits}, uprev,
        uprev2, f, t, dt, reltol, p, calck,
        ::Val{V}, verbose
    ) where {
        T <: Tuple, V, uEltypeNoUnits,
        uBottomEltypeNoUnits, tTypeNoUnits,
    }
    return Expr(
        :tuple,
        map(1:length(T.types)) do i
            :(
                alg_cache(
                    algs[$i], u, rate_prototype, uEltypeNoUnits,
                    uBottomEltypeNoUnits, tTypeNoUnits, uprev, uprev2, f, t, dt,
                    reltol, p, calck, Val($V), verbose
                )
            )
        end...
    )
end

alg_cache(alg::OrdinaryDiffEqAlgorithm, prob, callback::F) where {F} = ODEEmptyCache()

get_chunksize(cache::SciMLBase.DECache) = error("This cache does not have a chunksize.")
get_chunksize(cache::ODEChunkCache{CS}) where {CS} = CS
